name: Auto Approve
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  approve:
    # if: |
    #   (github.event.pull_request.user.login == github.repository_owner
    #   || github.event.pull_request.user.login == 'R-data91')
    #   && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
            github-token: ${{ secrets.AUTO_APPROVE_PAT }}
